title: Lucius Vo-Huynh
logo: "/images/logo.png?raw=true"
description:  
  Engineering and Science Enthusiast
  <b>quangnguyenvohuynh@gmail.com</b>
  <b>+ 84 (0) 396 957 043</b> 
show_downloads: true
theme: jekyll-theme-minimal