title: Lucius Vo-Huynh
logo: "/images/logo.png?raw=true"
description:  
  Engineering and Science Enthusiast
  <br>
  <b>Mail:</b> quangnguyenvohuynh@gmail.com

  <b>Phone:</b> + 84 (0) 396 957 043
show_downloads: true
theme: jekyll-theme-minimal