title: Quang-Nguyen Vo-Huynh
logo: "/images/logo.png?raw=true"
description: > 
  Engineering and Science Enthusiast
  <br></br>
  <a href = 'https://www.linkedin.com/in/quangnguyen-vohuynh/'>View My Linkedin Profile</a>
  <br></br>
  <a href = 'https://github.com/vohuynhquangnguyen'>View My GitHub Profile</a>
  <br></br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
